import { redirect } from "next/navigation"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import AppShell from "@/components/layout/AppShell"
import Link from "next/link"
import {
  Calculator,
  FileCheck2,
  LayoutGrid,
  Users,
  Anchor,
  TrendingUp,
  Mail,
  ExternalLink,
} from "lucide-react"

export const dynamic = "force-dynamic"

type Tile = {
  href: string
  external?: boolean
  title: string
  desc: string
  icon: any
  badge?: string
  status?: "live" | "wireframe" | "planned"
}

const QUOTING_TOOLS: Tile[] = [
  {
    href: "/tools/marex-440-quote.html",
    external: true,
    title: "Marex 440 — Configurator & Quoter",
    desc: "Full option-by-option build with live EUR/AUD tally. Emails completed quote to selected broker (Steve cc'd). Internal/Public modes.",
    icon: Calculator,
    badge: "M440",
    status: "wireframe",
  },
  {
    href: "#",
    title: "Marex 390 — Configurator & Quoter",
    desc: "Awaiting Steve's M390 wireframe / pricelist.",
    icon: Calculator,
    badge: "M390",
    status: "planned",
  },
  {
    href: "#",
    title: "Marex 310 — Configurator & Quoter",
    desc: "Awaiting Steve's M310 wireframe / pricelist.",
    icon: Calculator,
    badge: "M310",
    status: "planned",
  },
]

const REPORTING: Tile[] = [
  {
    href: "/board",
    title: "Lead Pipeline (Kanban)",
    desc: "All active leads grouped by stage. Drag to advance.",
    icon: LayoutGrid,
    status: "live",
  },
  {
    href: "/leads",
    title: "All Leads",
    desc: "Searchable list of every lead in the CRM.",
    icon: Users,
    status: "live",
  },
  {
    href: "#",
    title: "EDM QA Log",
    desc: "Pass/Fail/Blocked verdicts for every test EDM. Daily summary, failure-cause breakdown.",
    icon: FileCheck2,
    status: "planned",
  },
  {
    href: "#",
    title: "Quote Activity Report",
    desc: "Quotes generated by broker / model / week. Conversion funnel from quote → enquiry → sold.",
    icon: TrendingUp,
    status: "planned",
  },
  {
    href: "#",
    title: "Broker Lead Volume",
    desc: "Inbound enquiries per broker, time-to-first-touch, response SLAs.",
    icon: Mail,
    status: "planned",
  },
  {
    href: "#",
    title: "Active Fleet Listings",
    desc: "All current sale listings with price changes, days on market, EDM cadence.",
    icon: Anchor,
    status: "planned",
  },
]

function StatusPill({ status }: { status?: Tile["status"] }) {
  if (!status) return null
  const map = {
    live: "bg-emerald-100 text-emerald-700",
    wireframe: "bg-amber-100 text-amber-700",
    planned: "bg-slate-200 text-slate-600",
  }
  const label = { live: "Live", wireframe: "Wireframe", planned: "Planned" }[status]
  return <span className={`text-[10px] font-semibold uppercase tracking-wide px-1.5 py-0.5 rounded ${map[status]}`}>{label}</span>
}

function TileCard({ t }: { t: Tile }) {
  const Icon = t.icon
  const isPlanned = t.status === "planned"
  const inner = (
    <div
      className={`group relative h-full rounded-xl border bg-white p-5 transition-all ${
        isPlanned
          ? "border-slate-200 opacity-60"
          : "border-slate-200 hover:border-brand-500 hover:shadow-md hover:-translate-y-0.5"
      }`}
    >
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="w-10 h-10 rounded-lg bg-brand-50 text-brand-600 flex items-center justify-center flex-shrink-0">
          <Icon className="w-5 h-5" />
        </div>
        <div className="flex items-center gap-2">
          {t.badge && (
            <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-slate-900 text-white">
              {t.badge}
            </span>
          )}
          <StatusPill status={t.status} />
        </div>
      </div>
      <h3 className="font-semibold text-slate-900 text-sm mb-1.5 flex items-center gap-1.5">
        {t.title}
        {t.external && !isPlanned && <ExternalLink className="w-3.5 h-3.5 text-slate-400 group-hover:text-brand-600" />}
      </h3>
      <p className="text-xs text-slate-600 leading-relaxed">{t.desc}</p>
    </div>
  )
  if (isPlanned) return <div>{inner}</div>
  return t.external ? (
    <a href={t.href} target="_blank" rel="noopener noreferrer" className="block h-full">
      {inner}
    </a>
  ) : (
    <Link href={t.href} className="block h-full">
      {inner}
    </Link>
  )
}

function Section({ title, subtitle, tiles }: { title: string; subtitle: string; tiles: Tile[] }) {
  return (
    <section className="mb-10">
      <div className="mb-4">
        <h2 className="text-base font-bold text-slate-900">{title}</h2>
        <p className="text-xs text-slate-500 mt-0.5">{subtitle}</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {tiles.map((t, i) => (
          <TileCard key={i} t={t} />
        ))}
      </div>
    </section>
  )
}

export default async function FleetDashboardPage() {
  const session = await getServerSession(authOptions)
  if (!session) redirect("/login")

  return (
    <AppShell>
      <div className="px-8 py-6 max-w-7xl">
        <header className="mb-8">
          <div className="flex items-center gap-2 text-xs text-slate-500 mb-1">
            <span>Fleet</span>
            <span>›</span>
            <span>Dashboard</span>
          </div>
          <h1 className="text-2xl font-bold text-slate-900">Fleet Dashboard</h1>
          <p className="text-sm text-slate-600 mt-1">
            Pricing tools, quote configurators, and reporting across the Flagship fleet.
          </p>
        </header>

        <Section
          title="Quoting & Configuration Tools"
          subtitle="Per-model online configurators. Generate a priced quote, email it to the broker, push the lead to HubSpot."
          tiles={QUOTING_TOOLS}
        />

        <Section
          title="Reporting"
          subtitle="Live and planned reports across leads, EDMs, quotes, and listings."
          tiles={REPORTING}
        />

        <footer className="mt-12 pt-6 border-t border-slate-200 text-xs text-slate-500">
          <p>
            <strong className="text-slate-700">Wireframe note:</strong> the Marex 440 quoter is a static prototype hosted at{" "}
            <code className="bg-slate-100 px-1 py-0.5 rounded text-slate-700">/tools/marex-440-quote.html</code>. Reporting tiles
            marked "Planned" are placeholders awaiting backing data sources (HubSpot, EDM QA log, listings feed).
          </p>
        </footer>
      </div>
    </AppShell>
  )
}
